# Numpy

**Numerical Python**

Numpy supports n-dimentional Arrays

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### What is Array?

An array is a collection of items of same data type stored at contiguous memory locations. 



### Why Use NumPy?

Python have lists that serve the purpose of arrays, but they are slow to process hence numpy arrays are used



The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

### How are Numpy Arrays faster then Lists?

**Memory Usage**: Numpy arrays are more compact than lists. A list in Python stores an overhead of information (like data type) for every element. But numpy arrays are densely packed arrays of a homogeneous type, so you save space.

**Contiguous Memory Allocation**: Elements in numpy arrays are stored in contiguous memory blocks. This leads to better cache coherence and hence speed-up in retrieval or update of elements.

In [ ]:
!pip install numpy 
#if not installed

In [ ]:
import numpy as np

### Create a numpy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

**Create array using Python List**

In [ ]:
list=[1,2,3,4,5]
arr2=np.array(list)
print(arr2)

**Check data type of list and Array**

In [ ]:
print(type(list))
print(type(arr2))

### Create a 2D nupmy array

In [ ]:
arr3 = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])

print(arr3)

**Using python lists**

In [ ]:
list2=[6,7,8,9,10]
arr4=np.array([list,list2])
print(arr4)

### 3D Array

In [ ]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr5)

#### Check Dimention using **ndim**

In [ ]:
arr5.ndim

In [ ]:
arr4.ndim

### Accessing the Elements of Array

To access elements of Arrays we use indexisg the similar way we use for lists

**syntax= array[row_index, Column_index]**

In [ ]:
arr

In [ ]:
arr[0::2]

In [ ]:
arr2d

In [ ]:
arr2d[1,2]

In [ ]:
arr2d[:,0]

In [ ]:
arr3d

In [ ]:
arr3d[0,1,1:3]

In [ ]:
#1-D Array
arr[1]

In [ ]:
#2-D Array
arr4[0,2]

In [ ]:
#3-D Array
arr5[1,0,2]

## Slicing Operations on Arrays

**Syntax= array[start:end]**

We can also define the step, like this: [start:end:step].



### 1-D Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

print(arr)

In [ ]:
arr[1:5]

**steps**

In [ ]:
arr[1:5:1]

### 2-D Array

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])

print(arr)

In [ ]:
arr[1,2:5]

**If we don't pass start its considered 0**



In [ ]:
arr[0,:4]

**If we don't pass end its considered length of array in that dimension**

In [ ]:
arr[0,1:]

**to get all the rows from specific columns**

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:, 2:4])

In [ ]:
import numpy as np

### Check data type of array elements

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

**data types in NumPy**

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string

In [ ]:
arr = np.array([True, False,False])

print(arr.dtype)

In [ ]:
arr = np.array([5.6, 5.5])

print(arr.dtype)

We can also define type while creating arrays

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

## To check the shape of an Array .shape

In [ ]:
arr=np.array([[1,10],[2,20],[3,30]])
print(arr)

In [ ]:
arr.shape 

In [ ]:
arr=np.array([1,2,3,4,5])
arr.shape

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr.shape

### We can also reshape an array into desired shape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])

# arr_new = arr.reshape(5, 2)
arr_new

In [ ]:
arr_new.shape

In [ ]:
arr_new = arr.reshape(2, 2,3)


In [ ]:
arr_new

In [ ]:
arr_new.shape

**1-D to 3-D**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])

arr_new = arr.reshape(2, 2,3)
arr_new

### Joining 2 or more Arrays

**.concatenate()**

In [ ]:
arr1 = np.array([1, 2,3,4,5])

arr2 = np.array([6,7,8,9,10])

In [ ]:
arr2

In [ ]:
arr3=np.concatenate((arr1,arr2))
arr3

**2-D array**

In [ ]:
arr1 = np.array([[1, 2],[3,4]])

arr2 = np.array([[6,7],[8,9]])


In [ ]:
arr1

In [ ]:
arr3=np.concatenate((arr1,arr2),axis=1)

In [ ]:
arr3

In [ ]:
arr1 = np.array([1, 2,3,4,5])

arr2 = np.array([6,7,8,9,10])
arr3=np.concatenate((arr1,arr2))
arr3

## We can also use **stack**

use **vstack()** for vertical and **hstack()** for horizontal

In [ ]:
arr1 = np.array([[1, 2],[3,4]])

arr2 = np.array([[6,7],[8,9]])


In [ ]:
arr3=np.vstack((arr1,arr2))

In [ ]:
arr3


In [ ]:
arr3=np.hstack((arr1,arr2))
arr3

In [ ]:
arr1 = np.array([[1, 2],[3,4]])

arr2 = np.array([[6,7],[8,9]])
arr3=np.vstack((arr1,arr2))
arr3

In [ ]:
arr1 = np.array([[1, 2],[3,4]])

arr2 = np.array([[6,7],[8,9]])
arr3=np.hstack((arr1,arr2))
arr3

## There are various ways to create a numpy array

**An Array of all zeros**

syntax=np.zeros(shape)

In [ ]:
arr=np.zeros((4,5))
arr

**An Array of all ones**

syntax=np.ones(shape)

In [ ]:
arr=np.ones((4,5))
arr

**An array of a specfic integer**

syntax=np.full(shape,integer)

In [ ]:
arr=np.full((2,2),'stattech academy')
arr

**An array of identity matrixr**

syntax=np.eye(size)

In [ ]:
arr=np.eye(5)
arr

**An array of random integers**

syntax=np.ranom.randint(low,high,size)

In [ ]:
np.random.randint(10,100,(3,3))

**An array of evenly spread values between specific integers**

syntax=np.linspace(start,end,size)

In [ ]:
np.linspace(10,20,6)

**A diagonal matrix**

In [ ]:
np.diag([1,2,3,4,5,6,7])

In [ ]:
list=[1,2,3,4,5]
arr=np.array(list)
arr

In [1]:
import numpy as np

## Mathematical operations on arrays

In [2]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


**add elements of arrays**

In [3]:
arr1+arr2

array([5, 7, 9])

In [4]:
arr1-arr2

array([-3, -3, -3])

In [5]:
np.add(arr1,arr2)

array([5, 7, 9])

**multiply elements of array**

In [6]:
arr1*arr2

array([ 4, 10, 18])

In [7]:
np.multiply(arr1,arr2)

array([ 4, 10, 18])

**divide elements of array**

In [8]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [9]:
np.divide(arr1,arr2)

array([0.25, 0.4 , 0.5 ])

**square root**

In [10]:
np.sqrt(5)

2.23606797749979

**cube root**

In [11]:
np.cbrt(8) 

2.0

**power**

In [12]:
np.power(2,3)

8

All maths functions https://numpy.org/doc/stable/reference/routines.math.html

### other operations

**log base 10**

In [13]:
np.log10(arr1)

array([0.        , 0.30103   , 0.47712125])

In [14]:
np.log10(5)

0.6989700043360189

**log base 2**

In [15]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [16]:
np.log(5)

1.6094379124341003

**sin values of array**

In [17]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

**cosine values of array**

In [18]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

**add all elements of array**

In [19]:
np.sum(arr1)

6

**minimum value in an array**

In [20]:
np.min(arr1)

1

**max value in an array**

In [21]:
np.max(arr1)

3

**mean of an array**

In [22]:
np.mean(arr1)

2.0

**median of an array**

In [23]:
np.median(arr1)

2.0

**Create a copy of an array**

In [24]:
l=np.copy(arr1)

In [25]:
l

array([1, 2, 3])

### Set operations on array

In [27]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([5,6,7,8,9,10])


In [28]:
np.setdiff1d(arr1,arr2)

array([1, 2, 3, 4])

In [29]:
np.intersect1d(arr1,arr2)

array([5, 6])

In [30]:
np.union1d(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])