# Pandas

Pandas is a software library written for the Python programming language for data manipulation and analysis. 

In 2008, pandas development began at AQR Capital Management. By the end of 2009 it had been open sourced, and is actively supported today by a community of like-minded individuals around the world who contribute their valuable time and energy to help make open source pandas possible. 

**Library Highlights**

* A fast and efficient DataFrame object for data manipulation with integrated indexing;

* Tools for reading and writing data between in-memory data structures and different formats: CSV and text files, Microsoft Excel, SQL databases, and the fast HDF5 format;

* Intelligent data alignment and integrated handling of missing data: gain automatic label-based alignment in computations and easily manipulate messy data into an orderly form;

* Flexible reshaping and pivoting of data sets;

* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;

* Columns can be inserted and deleted from data structures for size mutability;

* Aggregating or transforming data with a powerful group by engine allowing split-apply-combine operations on data sets;

* High performance merging and joining of data sets;

* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;

* Time series-functionality: date range generation and frequency conversion, moving window statistics, date shifting and lagging. Even create domain-specific time offsets and join time series without losing data;

* Highly optimized for performance, with critical code paths written in Cython or C.

* Python with pandas is in use in a wide variety of academic and commercial domains, including Finance, Neuroscience, Economics, Statistics, Advertising, Web Analytics, and more.

## Installation of Pandas

In [ ]:
!pip install pandas

## Import Pandas

In [1]:
import pandas

Pandas is usually imported under the pd alias

In [2]:
import pandas as pd

**Check version**

In [3]:
print(pd.__version__)

2.1.4


**We can create a dictionary and change it to pandas DataFrame**

In [4]:
dataset = {
  'bikes': ["Bullet", "java", "hero"],
  'cc': [350, 200, 125]
}

pd.DataFrame(dataset)

bikes   cc
0  Bullet  350
1    java  200
2    hero  125

## Series

One-dimensional ndarray with axis labels 

pandas.Series(data=None, index=None, dtype=None, name=None, copy=None, fastpath=_NoDefault.no_default)[source]


In [5]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'b', 'c'])
ser

a    1
b    2
c    3
dtype: int64

In [6]:
a = [1, 7, 2]

var = pd.Series(a)
var

0    1
1    7
2    2
dtype: int64

In [7]:
a = [1, 2, 3]

var = pd.Series(a, index = ["a", "b", "c"])
var

a    1
b    2
c    3
dtype: int64

## DataFrame

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)


In [8]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

**We can also use numpy arrays**

In [9]:
import numpy as np

arr=np.random.randint(1,100,(10,4))
print(arr)

[[92 58 47  1]
 [68 44 73 30]
 [62 77 93  7]
 [31 73 69 34]
 [74 98 77 25]
 [51 69 58  6]
 [46 23 84 34]
 [63 16 25 93]
 [53 25  8 37]
 [21 81 81  5]]


In [10]:
pd.DataFrame(arr)

0   1   2   3
0  92  58  47   1
1  68  44  73  30
2  62  77  93   7
3  31  73  69  34
4  74  98  77  25
5  51  69  58   6
6  46  23  84  34
7  63  16  25  93
8  53  25   8  37
9  21  81  81   5

**column**

We can name these columns

In [11]:
df=pd.DataFrame(arr,columns=['a','b','c','d'])
df

a   b   c   d
0  92  58  47   1
1  68  44  73  30
2  62  77  93   7
3  31  73  69  34
4  74  98  77  25
5  51  69  58   6
6  46  23  84  34
7  63  16  25  93
8  53  25   8  37
9  21  81  81   5

In [12]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

**Index**

In [13]:
dataset = {
  'bikes': ["Bullet", "java", "hero"],
  'cc': [350, 200, 125]
}

df=pd.DataFrame(dataset,index=["a","b","c"])
df

bikes   cc
a  Bullet  350
b    java  200
c    hero  125

In [14]:
df.index

Index(['a', 'b', 'c'], dtype='object')

## CSV file to Pandas DataFrame

In [15]:
df=pd.read_csv('Housing.csv')

In [16]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

### Excel file to Dataframe

In [17]:
!pip install openpyxl


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
df2=pd.read_excel("Housing.xlsx")

In [19]:
df2

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

## Some important methods applied on a DataFrame

**head()**

 Returns the first  few rows of a dataframe

In [20]:

df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

 **tail()**

Returns the last few rows of a dataframe

In [21]:
df.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

**info(): -** Provides information about the dataframe, including the data types of each column, the number of rows and columns, and the memory usage.

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


**describe(): -** Provides summary statistics for each column of the dataframe, such as the mean, median, standard deviation, and minimum and maximum values.

In [23]:
df.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

**sort_values(): -** Sorts the dataframe by one or more columns.

In [24]:
df.sort_values(by=['price'])

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
544   1750000  3850         3          1        2      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
541   1767150  2400         3          1        1       no        no       no   
540   1820000  3000         2          1        1      yes        no      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
4    11410000  7420         4          1        2      yes       yes      yes   
3    12215000  7500         4          2        2      yes        no      yes   
2    12250000  9960         3          2        2      yes        no      yes   
1    12250000  8960         4          4        4      yes        no       no   
0    13300000  7420         4          2        3      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
544              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
542              no              no        0       no      unfurnished  
541              no              no        0       no   semi-furnished  
540              no              no        2       no      unfurnished  
..              ...             ...      ...      ...              ...  
4                no             yes        2       no        furnished  
3                no             yes        3      yes        furnished  
2                no              no        2      yes   semi-furnished  
1                no             yes        3       no        furnished  
0                no             yes        2      yes        furnished  

[545 rows x 13 columns]

In [25]:
df.sort_values(by=['price','area'])

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
543   1750000  2910         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
544   1750000  3850         3          1        2      yes        no       no   
541   1767150  2400         3          1        1       no        no       no   
540   1820000  3000         2          1        1      yes        no      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
4    11410000  7420         4          1        2      yes       yes      yes   
3    12215000  7500         4          2        2      yes        no      yes   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
0    13300000  7420         4          2        3      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
543              no              no        0       no        furnished  
542              no              no        0       no      unfurnished  
544              no              no        0       no      unfurnished  
541              no              no        0       no   semi-furnished  
540              no              no        2       no      unfurnished  
..              ...             ...      ...      ...              ...  
4                no             yes        2       no        furnished  
3                no             yes        3      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
0                no             yes        2      yes        furnished  

[545 rows x 13 columns]

**groupby(): -** Groups the dataframe by one or more columns and applies a function to each group.

DataFrame.groupby(by=None, axis=_NoDefault.no_default, level=None, as_index=True, sort=True, group_keys=True, observed=_NoDefault.no_default, dropna=True)

In [26]:
dataset = {
  'brand': ["lenovo", "lenovo", "hp"],
  'price': [35000, 43500, 32250]
}

df=pd.DataFrame(dataset,index=["a","b","c"])
df

brand  price
a  lenovo  35000
b  lenovo  43500
c      hp  32250

In [27]:
df.groupby('brand').mean()

price
brand          
hp      32250.0
lenovo  39250.0

In [28]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})
df



Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [29]:
df.groupby(['Animal']).mean()

Max Speed
Animal           
Falcon      375.0
Parrot       25.0

In [30]:
arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]
index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
                  index=index)
df


Max Speed
Animal Type              
Falcon Captive      390.0
       Wild         350.0
Parrot Captive       30.0
       Wild          20.0

In [31]:

df.groupby(level=0).mean()


Max Speed
Animal           
Falcon      370.0
Parrot       25.0

In [32]:
df.groupby(level=1).mean()


Max Speed
Type              
Captive      210.0
Wild         185.0

In [33]:

df.groupby(level="Type").mean()


Max Speed
Type              
Captive      210.0
Wild         185.0

**merge(): -** Merge two DataFrames together on a common column.

DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=None, indicator=False, validate=None)

In [34]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
df1

lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [35]:
df2

rkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

In [36]:
newdf = df1.merge(df2, how='left')
newdf

lkey  value rkey
0  foo      1  NaN
1  bar      2  NaN
2  baz      3  NaN
3  foo      5  foo

In [37]:
newdf = df1.merge(df2, how='outer')
newdf

lkey  value rkey
0  foo      1  NaN
1  bar      2  NaN
2  baz      3  NaN
3  foo      5  foo
4  NaN      6  bar
5  NaN      7  baz
6  NaN      8  foo

In [38]:
df1.merge(df2, left_on='lkey', right_on='rkey')


lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

In [39]:
df1

lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

**join(): -** Join two DataFrames together on a common index.

DataFrame.join(other, on=None, how='left', lsuffix='', rsuffix='', sort=False, validate=None)

In [40]:
df1.join(df2,lsuffix='_a', rsuffix='_b')

lkey  value_a rkey  value_b
0  foo        1  foo        5
1  bar        2  bar        6
2  baz        3  baz        7
3  foo        5  foo        8

**copy():** To create copy of a dataframe

In [41]:
df=pd.read_csv('Housing.csv')
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [42]:
copy_df=df.copy()
copy_df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

**concat():** The concat() method concatenates two DataFrames together.

pandas.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=None)

In [43]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
df1

letter  number
0      a       1
1      b       2

In [44]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df2


letter  number
0      c       3
1      d       4

In [45]:
pd.concat([df1, df2])


letter  number
0      a       1
1      b       2
0      c       3
1      d       4

## Manipulating dataframe

### Addding a Column

In [46]:
copy_df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [47]:
copy_df['priceinK']=copy_df['price']/1000
copy_df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  priceinK  
0              no             yes        2      yes        furnished   13300.0  
1              no             yes        3       no        furnished   12250.0  
2              no              no        2      yes   semi-furnished   12250.0  
3              no             yes        3      yes        furnished   12215.0  
4              no             yes        2       no        furnished   11410.0

### Droping a column

**drop():** The drop() method drops a specified row or column from the DataFrame.

DataFrame.drop(labels=None, *, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise'

In [48]:
copy_df.drop(columns=['mainroad',""])

price  area  bedrooms  bathrooms  stories guestroom basement  \
0    13300000  7420         4          2        3        no       no   
1    12250000  8960         4          4        4        no       no   
2    12250000  9960         3          2        2        no      yes   
3    12215000  7500         4          2        2        no      yes   
4    11410000  7420         4          1        2       yes      yes   
..        ...   ...       ...        ...      ...       ...      ...   
540   1820000  3000         2          1        1        no      yes   
541   1767150  2400         3          1        1        no       no   
542   1750000  3620         2          1        1        no       no   
543   1750000  2910         3          1        1        no       no   
544   1750000  3850         3          1        2        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished   
1                no             yes        3       no        furnished   
2                no              no        2      yes   semi-furnished   
3                no             yes        3      yes        furnished   
4                no             yes        2       no        furnished   
..              ...             ...      ...      ...              ...   
540              no              no        2       no      unfurnished   
541              no              no        0       no   semi-furnished   
542              no              no        0       no      unfurnished   
543              no              no        0       no        furnished   
544              no              no        0       no      unfurnished   

     priceinK  
0    13300.00  
1    12250.00  
2    12250.00  
3    12215.00  
4    11410.00  
..        ...  
540   1820.00  
541   1767.15  
542   1750.00  
543   1750.00  
544   1750.00  

[545 rows x 13 columns]

In [50]:
copy_df.drop(index=2)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
5    10850000  7500         3          3        1      yes        no      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished   
1                no             yes        3       no        furnished   
3                no             yes        3      yes        furnished   
4                no             yes        2       no        furnished   
5                no             yes        2      yes   semi-furnished   
..              ...             ...      ...      ...              ...   
540              no              no        2       no      unfurnished   
541              no              no        0       no   semi-furnished   
542              no              no        0       no      unfurnished   
543              no              no        0       no        furnished   
544              no              no        0       no      unfurnished   

     priceinK  
0    13300.00  
1    12250.00  
3    12215.00  
4    11410.00  
5    10850.00  
..        ...  
540   1820.00  
541   1767.15  
542   1750.00  
543   1750.00  
544   1750.00  

[544 rows x 14 columns]

In [52]:
copy_df.drop('mainroad',axis=1, inplace=True )

In [53]:
copy_df.head()

price  area  bedrooms  bathrooms  stories guestroom basement  \
0  13300000  7420         4          2        3        no       no   
1  12250000  8960         4          4        4        no       no   
2  12250000  9960         3          2        2        no      yes   
3  12215000  7500         4          2        2        no      yes   
4  11410000  7420         4          1        2       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  priceinK  
0              no             yes        2      yes        furnished   13300.0  
1              no             yes        3       no        furnished   12250.0  
2              no              no        2      yes   semi-furnished   12250.0  
3              no             yes        3      yes        furnished   12215.0  
4              no             yes        2       no        furnished   11410.0

### Check duplicates in data

**duplicated**
Return boolean Series denoting duplicate rows.

In [54]:
copy_df.duplicated().sum()

0

**drop_duplicates:** Return DataFrame with duplicate rows removed

In [55]:
copy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   price             545 non-null    int64  
 1   area              545 non-null    int64  
 2   bedrooms          545 non-null    int64  
 3   bathrooms         545 non-null    int64  
 4   stories           545 non-null    int64  
 5   guestroom         545 non-null    object 
 6   basement          545 non-null    object 
 7   hotwaterheating   545 non-null    object 
 8   airconditioning   545 non-null    object 
 9   parking           545 non-null    int64  
 10  prefarea          545 non-null    object 
 11  furnishingstatus  545 non-null    object 
 12  priceinK          545 non-null    float64
dtypes: float64(1), int64(6), object(6)
memory usage: 55.5+ KB


In [56]:
copy_df.drop_duplicates()

price  area  bedrooms  bathrooms  stories guestroom basement  \
0    13300000  7420         4          2        3        no       no   
1    12250000  8960         4          4        4        no       no   
2    12250000  9960         3          2        2        no      yes   
3    12215000  7500         4          2        2        no      yes   
4    11410000  7420         4          1        2       yes      yes   
..        ...   ...       ...        ...      ...       ...      ...   
540   1820000  3000         2          1        1        no      yes   
541   1767150  2400         3          1        1        no       no   
542   1750000  3620         2          1        1        no       no   
543   1750000  2910         3          1        1        no       no   
544   1750000  3850         3          1        2        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished   
1                no             yes        3       no        furnished   
2                no              no        2      yes   semi-furnished   
3                no             yes        3      yes        furnished   
4                no             yes        2       no        furnished   
..              ...             ...      ...      ...              ...   
540              no              no        2       no      unfurnished   
541              no              no        0       no   semi-furnished   
542              no              no        0       no      unfurnished   
543              no              no        0       no        furnished   
544              no              no        0       no      unfurnished   

     priceinK  
0    13300.00  
1    12250.00  
2    12250.00  
3    12215.00  
4    11410.00  
..        ...  
540   1820.00  
541   1767.15  
542   1750.00  
543   1750.00  
544   1750.00  

[545 rows x 13 columns]

### Locating a row 

**iloc** Purely integer-location based indexing for selection by position.

In [63]:
data.head()


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [67]:
data.iloc[544]

price                   1750000
area                       3850
bedrooms                      3
bathrooms                     1
stories                       2
mainroad                    yes
guestroom                    no
basement                     no
hotwaterheating              no
airconditioning              no
parking                       0
prefarea                     no
furnishingstatus    unfurnished
Name: 544, dtype: object

In [68]:
data.iloc[0:3]

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished

In [69]:
data.iloc[[0,1,2,3],[0,2]]

price  bedrooms
0  13300000         4
1  12250000         4
2  12250000         3
3  12215000         4

In [70]:
data.iloc[0:4,[0,2]]

price  bedrooms
0  13300000         4
1  12250000         4
2  12250000         3
3  12215000         4

In [71]:
data.iloc[0:3,0:3]

price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3

**loc:**
Access a group of rows and columns by label(s) or a boolean array.

In [73]:
data.loc[2,'furnishingstatus']

'semi-furnished'

In [74]:
data.loc[3,'furnishingstatus']

'furnished'

In [78]:
data.loc[0:5,['hotwaterheating'	,'airconditioning','furnishingstatus']]

hotwaterheating airconditioning furnishingstatus
0              no             yes        furnished
1              no             yes        furnished
2              no              no   semi-furnished
3              no             yes        furnished
4              no             yes        furnished
5              no             yes   semi-furnished

### Renaming a column 

**rename()** Rename columns or index labels.

DataFrame.rename(mapper=None, *, index=None, columns=None, axis=None, copy=None, inplace=False, level=None, errors='ignore')


In [79]:
data_new=data.rename(columns={"price":"PRICE","area":"AREA"})
data_new.head()

PRICE  AREA  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [80]:
data_new=data.rename(index={2:"Two",3:"Three"})
data_new.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom  \
0      13300000  7420         4          2        3      yes        no   
1      12250000  8960         4          4        4      yes        no   
Two    12250000  9960         3          2        2      yes        no   
Three  12215000  7500         4          2        2      yes        no   
4      11410000  7420         4          1        2      yes       yes   

      basement hotwaterheating airconditioning  parking prefarea  \
0           no              no             yes        2      yes   
1           no              no             yes        3       no   
Two        yes              no              no        2      yes   
Three      yes              no             yes        3      yes   
4          yes              no             yes        2       no   

      furnishingstatus  
0            furnished  
1            furnished  
Two     semi-furnished  
Three        furnished  
4            furnished

## Missing Values 

### Finding Missing Values

In [ ]:
df=pd.read_csv('Housing_with_null.csv')

In [ ]:
df.info()

In [ ]:
a=df.isnull()
a

**value_count:** Return a Series containing the frequency of each distinct row in the Dataframe.

In [ ]:
a.value_counts('bedrooms')

In [ ]:
a.value_counts('parking')

In [ ]:
a.value_counts('furnishingstatus')

**Note:** Value count is majorly used to understand data

### Another way to check total null values

In [ ]:
df.isnull().sum()

In [ ]:
df.head()

## Traeating NUll Values

**drop null values**

In [58]:
data=df.copy()

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [60]:
data=data.dropna()


In [61]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


**Imputing the missing values**

In [ ]:
data=df.copy()
data.info()

**fillna:** Fill NA/NaN values using the specified method.

DataFrame.fillna(value=None, *, method=None, axis=None, inplace=False, limit=None, downcast=_NoDefault.no_default)

inplace=True modifies the DataFrame in place, meaning it will change the original DataFrame directly without creating a copy

In [ ]:
data=data.fillna(0)

In [ ]:
data.isnull().sum()

In [ ]:
data.head()

## Filling with mean/ median

In [ ]:
data=df.copy()
data.isnull().sum()

In [ ]:
mean=data['bedrooms'].mean()
mean

In [ ]:
median=data['bedrooms'].median()
median

In [ ]:
data['bedrooms']=data['bedrooms'].fillna(median) 
# df=df.fillna(0)

In [ ]:
data.isnull().sum()

In [ ]:



p_median=data['parking'].median()
print(p_median)


In [ ]:
data['parking']=data['parking'].fillna(p_median)
data.isnull().sum()

In [ ]:
data.info()

In [ ]:
data['furnishingstatus'].value_counts()

In [ ]:
null_furnishingstatus_data = data[data['furnishingstatus'].isnull()]
null_furnishingstatus_data

In [ ]:
data['furnishingstatus'].fillna('unknown', inplace=True)


In [ ]:
data['furnishingstatus'].value_counts()

In [ ]:
data.isnull().sum()

## Finding relationship between different variables

**corr():** Compute pairwise correlation of columns, excluding NA/null values.

DataFrame.corr(method='pearson', min_periods=1, numeric_only=False)

In [81]:
corr_data=data.loc[:,['price','area','bedrooms'	,'bathrooms','stories','parking']]
corr_data

price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [82]:
corr_data.corr()

price      area  bedrooms  bathrooms   stories   parking
price      1.000000  0.535997  0.366494   0.517545  0.420712  0.384394
area       0.535997  1.000000  0.151858   0.193820  0.083996  0.352980
bedrooms   0.366494  0.151858  1.000000   0.373930  0.408564  0.139270
bathrooms  0.517545  0.193820  0.373930   1.000000  0.326165  0.177496
stories    0.420712  0.083996  0.408564   0.326165  1.000000  0.045547
parking    0.384394  0.352980  0.139270   0.177496  0.045547  1.000000